-- MySQL Script generated by MySQL Workbench
-- Sun Feb 15 16:34:09 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`FAMILIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FAMILIA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`FAMILIA` (
  `id_familia` DECIMAL(9) NOT NULL,
  `ciudad` VARCHAR(45) NULL,
  `nombre_difunto` VARCHAR(45) NULL,
  `apellidos_difunto` VARCHAR(45) NULL,
  PRIMARY KEY (`id_familia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PEDIDO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PEDIDO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PEDIDO` (
  `id_pedido` INT NOT NULL,
  `FAMILIA_id_familia` DECIMAL(9) NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_PEDIDO_FAMILIA_idx` (`FAMILIA_id_familia` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_FAMILIA`
    FOREIGN KEY (`FAMILIA_id_familia`)
    REFERENCES `mydb`.`FAMILIA` (`id_familia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SERVICIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SERVICIO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SERVICIO` (
  `id_servicio` VARCHAR(20) NOT NULL,
  `nombre_servicio` VARCHAR(45) NULL,
  `descripcion` VARCHAR(200) NULL,
  `precio_base` DOUBLE NULL,
  PRIMARY KEY (`id_servicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EMPLEADOS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADOS` (
  `DNI` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `carnet` TINYINT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Detalle_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Detalle_pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Detalle_pedido` (
  `PEDIDO_id_pedido` INT NOT NULL,
  `SERVICIO_id_servicio` VARCHAR(20) NOT NULL,
  `fecha_servicio` DATE NULL,
  `EMPLEADOS_DNI` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`PEDIDO_id_pedido`, `SERVICIO_id_servicio`),
  INDEX `fk_PEDIDO_has_SERVICIO_SERVICIO1_idx` (`SERVICIO_id_servicio` ASC) VISIBLE,
  INDEX `fk_PEDIDO_has_SERVICIO_PEDIDO1_idx` (`PEDIDO_id_pedido` ASC) VISIBLE,
  INDEX `fk_Detalle_pedido_EMPLEADOS1_idx` (`EMPLEADOS_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_has_SERVICIO_PEDIDO1`
    FOREIGN KEY (`PEDIDO_id_pedido`)
    REFERENCES `mydb`.`PEDIDO` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_has_SERVICIO_SERVICIO1`
    FOREIGN KEY (`SERVICIO_id_servicio`)
    REFERENCES `mydb`.`SERVICIO` (`id_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_pedido_EMPLEADOS1`
    FOREIGN KEY (`EMPLEADOS_DNI`)
    REFERENCES `mydb`.`EMPLEADOS` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VEHICULO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`VEHICULO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`VEHICULO` (
  `matricula` VARCHAR(8) NOT NULL,
  `color` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VIAJE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`VIAJE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`VIAJE` (
  `fecha_inicio` DATETIME NULL,
  `fecha_fin` DATETIME NULL,
  `km_total` VARCHAR(45) NULL,
  `precioKm` FLOAT NULL,
  `EMPLEADOS_DNI` VARCHAR(9) NOT NULL,
  `PEDIDO_id_pedido` INT NOT NULL,
  `VEHICULO_matricula` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`PEDIDO_id_pedido`),
  INDEX `fk_VIAJE_VEHICULO1_idx` (`VEHICULO_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_VIAJE_EMPLEADOS1`
    FOREIGN KEY (`EMPLEADOS_DNI`)
    REFERENCES `mydb`.`EMPLEADOS` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VIAJE_PEDIDO1`
    FOREIGN KEY (`PEDIDO_id_pedido`)
    REFERENCES `mydb`.`PEDIDO` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VIAJE_VEHICULO1`
    FOREIGN KEY (`VEHICULO_matricula`)
    REFERENCES `mydb`.`VEHICULO` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
